// Structured data builders — plain functions returning JSON-serializable objects,
// so schema is generated by code (never a plugin) and can't drift or double-encode.

const SITE_URL = 'https://elc.com.sa';

export function organizationSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    name: 'ELC',
    url: SITE_URL,
    // TODO: replace with the corrected legal/GBP name once the NAP mismatch is resolved
    // ("Knowledge Edifice Institute" vs "ELC" — see plan doc section 8).
    address: {
      '@type': 'PostalAddress',
      streetAddress: '', // TODO: fill from corrected GBP listing
      addressLocality: '',
      addressCountry: 'SA',
    },
    sameAs: [
      // TODO: add YouTube, LinkedIn — currently missing per audit
    ],
  };
}

export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function courseSchema(course: {
  name: string;
  description: string;
  price: number;
  currency?: string;
  durationText: string;
  url: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: course.name,
    description: course.description,
    provider: { '@type': 'EducationalOrganization', name: 'ELC', sameAs: SITE_URL },
    hasCourseInstance: {
      '@type': 'CourseInstance',
      courseMode: 'Onsite',
      duration: course.durationText,
    },
    offers: {
      '@type': 'Offer',
      price: course.price,
      priceCurrency: course.currency ?? 'SAR',
      url: course.url,
    },
  };
}
