// Structured data builders — plain functions returning JSON-serializable objects,
// so schema is generated by code (never a plugin) and can't drift or double-encode.

const SITE_URL = 'https://elc.com.sa';

/**
 * @param aggregateRating Only ever pass real numbers from lib/googleReviews.ts's
 *   GoogleReviewsResult — never fabricated. Omit entirely if reviews aren't
 *   configured yet (the build already does this — see src/pages/{en,ar}/index.astro).
 */
export function organizationSchema(
  aggregateRating?: { rating: number; reviewCount: number },
  locale: 'en' | 'ar' = 'en'
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    name: locale === 'ar' ? 'معهد صرح المعرفة' : 'ELC',
    alternateName: locale === 'ar' ? 'ELC' : 'معهد صرح المعرفة',
    url: SITE_URL,
    foundingDate: '2010', // real, from the live site's About page
    email: 'info@elc.com.sa', // real
    telephone: '+966591799917',
    contactPoint: [
      { '@type': 'ContactPoint', telephone: '+966591799917', contactType: 'admissions' },
      { '@type': 'ContactPoint', telephone: '+966546656000', contactType: 'WhatsApp' },
      { '@type': 'ContactPoint', telephone: '+966126305553', contactType: 'customer service' },
      { '@type': 'ContactPoint', telephone: '+966126306030', contactType: 'customer service' },
    ],
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Abdullah Al-Suleiman Street, Al Fayahaa District',
      addressLocality: 'Jeddah',
      addressRegion: 'Makkah Province',
      addressCountry: 'SA',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 21.4971147,
      longitude: 39.2156796,
    },
    // Real, from the live site's footer/social links.
    sameAs: [
      'https://www.facebook.com/ELCJeddah',
      'https://twitter.com/elcjeddah',
      'https://www.instagram.com/elcjeddah',
      'https://www.snapchat.com/add/elcjeddah',
      // TODO: add YouTube, LinkedIn — currently missing per audit
    ],
    ...(aggregateRating && {
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: aggregateRating.rating,
        reviewCount: aggregateRating.reviewCount,
      },
    }),
  };
}

export function localBusinessSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    '@id': `${SITE_URL}/#organization`,
    name: 'ELC',
    alternateName: 'معهد صرح المعرفة',
    url: SITE_URL,
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Abdullah Al-Suleiman Street, Al Fayahaa District',
      addressLocality: 'Jeddah',
      addressRegion: 'Makkah Province',
      addressCountry: 'SA',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 21.4971147,
      longitude: 39.2156796,
    },
    telephone: '+966591799917',
  };
}

export function faqPageSchema(faqs: { question: string; answer: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: { '@type': 'Answer', text: faq.answer },
    })),
  };
}

export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function courseSchema(course: {
  name: string;
  description: string;
  price?: number;
  currency?: string;
  durationText?: string;
  url: string;
  providerName?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: course.name,
    description: course.description,
    provider: { '@type': 'EducationalOrganization', name: course.providerName ?? 'ELC', sameAs: SITE_URL },
    hasCourseInstance: {
      '@type': 'CourseInstance',
      courseMode: 'Onsite',
      ...(course.durationText ? { duration: course.durationText } : {}),
    },
    ...(course.price !== undefined ? {
      offers: {
        '@type': 'Offer',
        price: course.price,
        priceCurrency: course.currency ?? 'SAR',
        url: course.url,
      },
    } : {}),
  };
}
