// Structured data builders — plain functions returning JSON-serializable objects,
// so schema is generated by code (never a plugin) and can't drift or double-encode.

const SITE_URL = 'https://elc.com.sa';

/**
 * @param aggregateRating Only ever pass real numbers from lib/googleReviews.ts's
 *   GoogleReviewsResult — never fabricated. Omit entirely if reviews aren't
 *   configured yet (the build already does this — see src/pages/{en,ar}/index.astro).
 */
export function organizationSchema(
  aggregateRating?: { rating: number; reviewCount: number },
  locale: 'en' | 'ar' = 'en'
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    '@id': `${SITE_URL}/#organization`,
    name: locale === 'ar' ? 'معهد صرح المعرفة' : 'ELC',
    alternateName: locale === 'ar' ? 'ELC' : 'معهد صرح المعرفة',
    url: SITE_URL,
    foundingDate: '2010', // real, from the live site's About page
    email: 'info@elc.com.sa', // real
    telephone: '+966591799917',
    contactPoint: [
      { '@type': 'ContactPoint', telephone: '+966591799917', contactType: 'admissions' },
      { '@type': 'ContactPoint', telephone: '+966546656000', contactType: 'WhatsApp' },
      { '@type': 'ContactPoint', telephone: '+966126305553', contactType: 'customer service' },
      { '@type': 'ContactPoint', telephone: '+966126306030', contactType: 'customer service' },
    ],
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Abdullah Al-Suleiman Street, Al Fayahaa District',
      addressLocality: 'Jeddah',
      addressRegion: 'Makkah Province',
      addressCountry: 'SA',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 21.4971147,
      longitude: 39.2156796,
    },
    // Real, from the live site's footer/social links plus YouTube/LinkedIn
    // confirmed live and active during a later audit pass.
    sameAs: [
      'https://www.facebook.com/ELCJeddah',
      'https://twitter.com/elcjeddah',
      'https://www.instagram.com/elcjeddah',
      'https://www.snapchat.com/add/elcjeddah',
      'https://www.youtube.com/c/ELCInst',
      'https://www.linkedin.com/company/elcjeddah',
    ],
    ...(aggregateRating && {
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: aggregateRating.rating,
        reviewCount: aggregateRating.reviewCount,
      },
    }),
  };
}

export function faqPageSchema(faqs: { question: string; answer: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: { '@type': 'Answer', text: faq.answer },
    })),
  };
}

export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function courseSchema(course: {
  name: string;
  description: string;
  price?: number;
  currency?: string;
  durationText?: string;
  url: string;
  providerName?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: course.name,
    description: course.description,
    provider: { '@type': 'EducationalOrganization', name: course.providerName ?? 'ELC', sameAs: SITE_URL },
    hasCourseInstance: {
      '@type': 'CourseInstance',
      courseMode: 'Onsite',
      ...(course.durationText ? { duration: course.durationText } : {}),
    },
    ...(course.price !== undefined ? {
      offers: {
        '@type': 'Offer',
        price: course.price,
        priceCurrency: course.currency ?? 'SAR',
        url: course.url,
      },
    } : {}),
  };
}

export function serviceSchema(service: {
  name: string;
  description: string;
  url: string;
  areaServed?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalService',
    '@id': `${service.url}#service`,
    name: service.name,
    description: service.description,
    provider: { '@type': 'EducationalOrganization', name: 'ELC', sameAs: SITE_URL },
    url: service.url,
    ...(service.areaServed && { areaServed: service.areaServed }),
  };
}

export function articleSchema(article: {
  headline: string;
  description: string;
  datePublished: string;
  dateModified?: string;
  author?: string;
  url: string;
  image?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: article.headline,
    description: article.description,
    datePublished: article.datePublished,
    ...(article.dateModified && { dateModified: article.dateModified }),
    author: { '@type': 'Organization', name: article.author ?? 'ELC' },
    publisher: { '@type': 'Organization', name: 'ELC', url: SITE_URL },
    url: article.url,
    ...(article.image && { image: article.image }),
  };
}

/**
 * LocalBusiness schema with complete GBP optimization
 * Used for Google Business Profile and local search visibility
 */
export function localBusinessSchema(
  locale: 'en' | 'ar' = 'en',
  businessHours?: { day: string; open: string; close: string }[]
) {
  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    '@id': `${SITE_URL}/#local-business`,
    name: locale === 'ar' ? 'معهد صرح المعرفة' : 'ELC - Knowledge Institute',
    alternateName: locale === 'ar' ? 'ELC' : 'معهد صرح المعرفة',
    description: locale === 'ar'
      ? 'معهد متخصص في تعليم اللغة الإنجليزية معتمد من المؤسسة العامة للتدريب التقني والمهني'
      : 'Accredited English language learning institute in Jeddah, Saudi Arabia',
    url: SITE_URL,
    telephone: '+966591799917',
    email: 'info@elc.com.sa',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Abdullah Al-Suleiman Street, Al Fayahaa District',
      addressLocality: 'Jeddah',
      addressRegion: 'Makkah Province',
      postalCode: '21413',
      addressCountry: 'SA',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 21.4971147,
      longitude: 39.2156796,
    },
    priceRange: '$$',
    image: `${SITE_URL}/favicon-180.png`,
    // Business hours (ISO 8601 format)
    ...(businessHours && businessHours.length > 0 && {
      openingHoursSpecification: businessHours.map(h => ({
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: h.day,
        opens: h.open,
        closes: h.close,
      })),
    }),
    sameAs: [
      'https://www.facebook.com/ELCJeddah',
      'https://twitter.com/elcjeddah',
      'https://www.instagram.com/elcjeddah',
      'https://www.youtube.com/c/ELCInst',
      'https://www.linkedin.com/company/elcjeddah',
    ],
  };
}

/**
 * AI-Optimized metadata helper
 * Adds markers for AI crawlers and summarization engines
 */
export function getAiMetadata(
  content: string,
  locale: 'en' | 'ar' = 'en'
) {
  return {
    // Machine-readable content summary for AI indexing
    aiSummary: content.slice(0, 500), // First 500 chars as AI summary
    // Keywords for AI understanding
    aiKeywords: locale === 'ar'
      ? ['دورات إنجليزي', 'تعليم اللغة', 'معهد معتمد', 'اختبار تحديد مستوى']
      : ['English courses', 'language learning', 'accredited institute', 'placement test'],
    // Content type hint for AI parsing
    contentType: 'EducationalContent',
    // AI accessibility marker
    aiAccessible: true,
  };
}
